// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteKeyPair(arg1:string):Promise<void>;

export function ExportPrivateKey(arg1:string):Promise<void>;

export function ExportPublicKey(arg1:string):Promise<void>;

export function GenerateKeyPairCmd(arg1:string):Promise<model.KeyPairInfo>;

export function GenerateSecureQR(arg1:model.IssuerConfig):Promise<model.QRGenerationResult>;

export function GetDocumentInfo(arg1:string):Promise<Record<string, any>>;

export function HashDocumentFile(arg1:string):Promise<string>;

export function ImportPrivateKey(arg1:string):Promise<model.KeyPairInfo>;

export function ImportPublicKey(arg1:string):Promise<model.KeyPairInfo>;

export function ListKeyPairs():Promise<Array<model.KeyPairInfo>>;

export function SaveQRImage(arg1:string):Promise<void>;

export function SaveSignedDocument(arg1:string):Promise<void>;

export function SelectDocument():Promise<string>;

export function SelectQRImage():Promise<string>;

export function SetDefaultKeyPair(arg1:string):Promise<void>;

export function VerifyDocument():Promise<model.VerificationResult>;

export function VerifyQRFromData(arg1:string):Promise<model.VerificationResult>;

export function VerifyQRFromImage(arg1:string):Promise<model.VerificationResult>;
