// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKeyPair(arg1) {
  return ObfuscatedCall(0, [arg1]);
}

export function ExportPrivateKey(arg1) {
  return ObfuscatedCall(1, [arg1]);
}

export function ExportPublicKey(arg1) {
  return ObfuscatedCall(2, [arg1]);
}

export function GenerateKeyPairCmd(arg1) {
  return ObfuscatedCall(3, [arg1]);
}

export function GenerateSecureQR(arg1) {
  return ObfuscatedCall(4, [arg1]);
}

export function GetDocumentInfo(arg1) {
  return ObfuscatedCall(5, [arg1]);
}

export function HashDocumentFile(arg1) {
  return ObfuscatedCall(6, [arg1]);
}

export function ImportPrivateKey(arg1) {
  return ObfuscatedCall(7, [arg1]);
}

export function ImportPublicKey(arg1) {
  return ObfuscatedCall(8, [arg1]);
}

export function ListKeyPairs() {
  return ObfuscatedCall(9, []);
}

export function SaveQRImage(arg1) {
  return ObfuscatedCall(10, [arg1]);
}

export function SaveSignedDocument(arg1) {
  return ObfuscatedCall(11, [arg1]);
}

export function SelectDocument() {
  return ObfuscatedCall(12, []);
}

export function SelectQRImage() {
  return ObfuscatedCall(13, []);
}

export function SetDefaultKeyPair(arg1) {
  return ObfuscatedCall(14, [arg1]);
}

export function VerifyDocument() {
  return ObfuscatedCall(15, []);
}

export function VerifyQRFromData(arg1) {
  return ObfuscatedCall(16, [arg1]);
}

export function VerifyQRFromImage(arg1) {
  return ObfuscatedCall(17, [arg1]);
}
